-- =====================================================================
-- 权盾智检 · 数据库一次性初始化（全新多租户，从零开始）
--
-- ⚠ 警告：本脚本会删除现有全部测试数据（试剂、库存、采购单），不可恢复！
--
-- 使用方法：
--   1. 打开 https://supabase.com/dashboard/project/eqgrtoeivuykemfferwb/sql/new
--   2. 粘贴本文件全部内容
--   3. 点击 Run，看到最后的表清单即初始化完成
-- =====================================================================

create extension if not exists pgcrypto;

-- ── 1) 清理旧的测试数据和旧版函数 ────────────────────────────────────

drop table if exists public.purchase_order_items cascade;
drop table if exists public.purchase_orders cascade;
drop table if exists public.stock_records cascade;
drop table if exists public.reagents cascade;
drop table if exists public.platform_admins cascade;
drop table if exists public.tenant_invites cascade;
drop table if exists public.tenant_members cascade;
drop table if exists public.tenants cascade;

do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'is_tenant_member', 'is_tenant_admin', 'is_platform_admin', 'claim_default_tenant',
        'create_tenant', 'create_platform_tenant', 'create_tenant_invite', 'accept_tenant_invite',
        'submit_stock_batch', 'create_restock_order', 'receive_purchase_order', 'save_reagent'
      )
  loop
    execute format('drop function %s cascade', fn.signature);
  end loop;
end $$;

-- ── 2) 租户（检验科）、成员、邀请码 ──────────────────────────────────

create table public.tenants (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  code        text not null,
  status      text not null default 'active' check (status in ('active', 'disabled')),
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);
create unique index tenants_code_lower_idx on public.tenants (lower(code));

create table public.tenant_members (
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null default 'employee' check (role in ('admin', 'employee')),
  created_at timestamptz not null default now(),
  primary key (tenant_id, user_id)
);
-- Enforce the one-account-one-lab rule in the database, including concurrent invite claims.
create unique index tenant_members_one_tenant_per_user_idx on public.tenant_members (user_id);

create table public.tenant_invites (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  code        text not null unique,
  role        text not null default 'employee' check (role in ('admin', 'employee')),
  created_by  uuid not null references auth.users(id) on delete restrict,
  expires_at  timestamptz not null default (now() + interval '7 days'),
  used_by     uuid references auth.users(id) on delete set null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index tenant_invites_tenant_idx on public.tenant_invites (tenant_id, created_at desc);

-- 平台管理员：只有这里的账号可以开通新检验科（商用授权入口）。
create table public.platform_admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_platform_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.platform_admins pa where pa.user_id = auth.uid());
$$;

-- ── 3) 业务表（自带 tenant_id，从零开始，不含任何测试数据）────────────

create table public.reagents (
  id                  bigint generated by default as identity primary key,
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  code                text not null default '',
  name                text not null,
  category            text not null default '',
  specification       text not null default '',
  manufacturer        text not null default '',
  unit                text not null default '盒',
  stock_quantity      integer not null default 0,
  min_stock           integer not null default 0,
  storage_condition   text not null default '',
  location            text not null default '',
  expiry_date         text not null default '',
  registration_number text not null default '',
  notes               text not null default '',
  scan_rule           text not null default '',
  scan_segments       jsonb not null default '[]'::jsonb,
  lot_number          text not null default '',
  production_date     text not null default '',
  raw_barcode         text not null default '',
  supplier            text not null default '',
  unit_price          numeric(12, 2) not null default 0,
  created_at          timestamptz not null default now()
);
create unique index reagents_tenant_code_idx on public.reagents (tenant_id, code) where code <> '';
create index reagents_tenant_idx on public.reagents (tenant_id, id);

create table public.stock_records (
  id              bigint generated by default as identity primary key,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  reagent_id      bigint not null references public.reagents(id) on delete restrict,
  type            text not null check (type in ('in', 'out')),
  quantity        integer not null check (quantity > 0),
  lot_number      text not null default '',
  expiry_date     text not null default '',
  production_date text not null default '',
  note            text not null default '',
  operator        text not null default '',
  department      text not null default '',
  reason          text not null default '',
  created_at      timestamptz not null default now()
);
create index stock_records_tenant_idx on public.stock_records (tenant_id, created_at desc);
create index stock_records_batch_idx on public.stock_records (tenant_id, reagent_id, lot_number, expiry_date, production_date);

create table public.purchase_orders (
  id         bigint generated by default as identity primary key,
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  status     text not null default 'submitted' check (status in ('submitted', 'received', 'cancelled')),
  note       text not null default '',
  item_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index purchase_orders_tenant_idx on public.purchase_orders (tenant_id, created_at desc);

create table public.purchase_order_items (
  id            bigint generated by default as identity primary key,
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  order_id      bigint not null references public.purchase_orders(id) on delete cascade,
  reagent_id    bigint not null references public.reagents(id) on delete restrict,
  quantity      integer not null check (quantity > 0),
  unit          text not null default '',
  name          text not null default '',
  manufacturer  text not null default '',
  specification text not null default '',
  supplier      text not null default ''
);
create index purchase_order_items_tenant_idx on public.purchase_order_items (tenant_id, order_id);

-- ── 4) 成员关系判定函数 ──────────────────────────────────────────────

create or replace function public.is_tenant_member(p_tenant_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.tenant_members m
    where m.tenant_id = p_tenant_id and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_tenant_admin(p_tenant_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.tenant_members m
    where m.tenant_id = p_tenant_id and m.user_id = auth.uid() and m.role = 'admin'
  );
$$;

-- ── 5) 创建检验科 / 邀请码 RPC ───────────────────────────────────────

create or replace function public.create_tenant(p_name text, p_code text)
returns public.tenants
language plpgsql security definer set search_path = public
as $$
declare
  result public.tenants;
  normalized_code text := upper(trim(p_code));
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if trim(coalesce(p_name, '')) = '' or normalized_code = '' then raise exception '检验科名称和编码不能为空'; end if;
  if exists (select 1 from public.tenant_members where user_id = auth.uid()) then
    raise exception '该账号已经加入检验科';
  end if;
  insert into public.tenants (name, code, created_by)
  values (trim(p_name), normalized_code, auth.uid())
  returning * into result;
  insert into public.tenant_members (tenant_id, user_id, role)
  values (result.id, auth.uid(), 'admin');
  return result;
end;
$$;

create or replace function public.create_tenant_invite(p_tenant_id uuid)
returns text
language plpgsql security definer set search_path = public
as $$
declare
  invite_code text;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以生成邀请码'; end if;
  invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
  insert into public.tenant_invites (tenant_id, code, created_by)
  values (p_tenant_id, invite_code, auth.uid());
  return invite_code;
end;
$$;

create or replace function public.accept_tenant_invite(p_code text)
returns public.tenants
language plpgsql security definer set search_path = public
as $$
declare
  invite_row public.tenant_invites;
  result public.tenants;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if exists (select 1 from public.tenant_members where user_id = auth.uid()) then
    raise exception '该账号已经加入检验科';
  end if;
  select * into invite_row from public.tenant_invites
  where code = upper(trim(p_code)) and used_by is null and expires_at > now()
  for update;
  if invite_row.id is null then raise exception '邀请码无效或已过期'; end if;
  begin
    insert into public.tenant_members (tenant_id, user_id, role)
    values (invite_row.tenant_id, auth.uid(), invite_row.role);
  exception when unique_violation then
    raise exception '该账号已经加入其他检验科或该邀请码已被使用';
  end;
  update public.tenant_invites set used_by = auth.uid(), used_at = now() where id = invite_row.id;
  select * into result from public.tenants where id = invite_row.tenant_id;
  return result;
end;
$$;

-- 平台管理员开通新检验科：创建租户并返回“开通码”（管理员角色邀请码）。
create or replace function public.create_platform_tenant(p_name text, p_code text)
returns text
language plpgsql security definer set search_path = public
as $$
declare
  new_tenant public.tenants;
  invite_code text;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if not public.is_platform_admin() then raise exception '只有平台管理员可以开通检验科'; end if;
  if trim(coalesce(p_name, '')) = '' or trim(coalesce(p_code, '')) = '' then raise exception '检验科名称和编码不能为空'; end if;
  insert into public.tenants (name, code, created_by)
  values (trim(p_name), upper(trim(p_code)), auth.uid())
  returning * into new_tenant;
  invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
  insert into public.tenant_invites (tenant_id, code, role, created_by)
  values (new_tenant.id, invite_code, 'admin', auth.uid());
  return invite_code;
end;
$$;

-- ── 6) 行级安全（RLS）：只能访问所属检验科的数据 ─────────────────────

alter table public.tenants enable row level security;
alter table public.tenant_members enable row level security;
alter table public.tenant_invites enable row level security;
alter table public.platform_admins enable row level security;
alter table public.reagents enable row level security;
alter table public.stock_records enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create policy platform_admins_self_select on public.platform_admins
  for select using (user_id = auth.uid());

create policy tenants_member_select on public.tenants
  for select using (public.is_tenant_member(id));

create policy tenant_members_self_or_admin_select on public.tenant_members
  for select using (user_id = auth.uid() or public.is_tenant_admin(tenant_id));

create policy tenant_invites_admin_select on public.tenant_invites
  for select using (public.is_tenant_admin(tenant_id));

create policy reagents_member_select on public.reagents
  for select using (public.is_tenant_member(tenant_id));
create policy reagents_admin_insert on public.reagents
  for insert with check (public.is_tenant_admin(tenant_id));
create policy reagents_admin_update on public.reagents
  for update using (public.is_tenant_admin(tenant_id)) with check (public.is_tenant_admin(tenant_id));
create policy reagents_admin_delete on public.reagents
  for delete using (public.is_tenant_admin(tenant_id));

create policy stock_records_member_select on public.stock_records
  for select using (public.is_tenant_member(tenant_id));
create policy purchase_orders_member_select on public.purchase_orders
  for select using (public.is_tenant_member(tenant_id));
create policy purchase_order_items_member_select on public.purchase_order_items
  for select using (public.is_tenant_member(tenant_id));

-- 表级权限：库存记录和采购单只能通过下面的 RPC 写入，员工不能直接改。
grant select on public.tenants, public.tenant_members, public.tenant_invites, public.platform_admins to authenticated;
grant select on public.reagents, public.stock_records, public.purchase_orders, public.purchase_order_items to authenticated;
-- Reagent metadata can be edited directly, but inserts and stock changes must go through audited RPCs.
revoke insert, update on public.reagents from public, anon, authenticated;
grant update (
  code, name, category, specification, manufacturer, unit, min_stock,
  storage_condition, location, expiry_date, registration_number, notes,
  scan_rule, scan_segments, lot_number, production_date, raw_barcode,
  supplier, unit_price
) on public.reagents to authenticated;
grant delete on public.reagents to authenticated;
revoke insert, update, delete on public.stock_records, public.purchase_orders, public.purchase_order_items from anon, authenticated;
revoke insert, update, delete on public.tenants, public.tenant_members, public.tenant_invites from anon, authenticated;

-- ── 7) 业务 RPC（函数内再次校验成员/管理员身份）──────────────────────

-- 试剂资料通过受控 RPC 保存；期初库存以入库流水原子记录，编辑资料永远不改库存。
create or replace function public.save_reagent(
  p_tenant_id uuid,
  p_id bigint,
  p_reagent jsonb,
  p_initial_stock integer,
  p_operator text
)
returns public.reagents
language plpgsql security definer set search_path = public
as $$
declare
  saved public.reagents;
  opening_stock integer := coalesce(p_initial_stock, 0);
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以保存试剂'; end if;
  if p_reagent is null or jsonb_typeof(p_reagent) is distinct from 'object' then raise exception '试剂资料格式错误'; end if;
  if opening_stock < 0 then raise exception '期初库存不能小于 0'; end if;

  if p_id is null then
    insert into public.reagents (
      tenant_id, code, name, category, specification, manufacturer, unit,
      stock_quantity, min_stock, storage_condition, location, expiry_date,
      registration_number, notes, scan_rule, scan_segments, lot_number,
      production_date, raw_barcode, supplier, unit_price
    ) values (
      p_tenant_id,
      coalesce(p_reagent->>'code', ''),
      coalesce(p_reagent->>'name', ''),
      coalesce(p_reagent->>'category', ''),
      coalesce(p_reagent->>'specification', ''),
      coalesce(p_reagent->>'manufacturer', ''),
      coalesce(p_reagent->>'unit', '盒'),
      0,
      coalesce(nullif(p_reagent->>'min_stock', '')::integer, 0),
      coalesce(p_reagent->>'storage_condition', ''),
      coalesce(p_reagent->>'location', ''),
      coalesce(p_reagent->>'expiry_date', ''),
      coalesce(p_reagent->>'registration_number', ''),
      coalesce(p_reagent->>'notes', ''),
      coalesce(p_reagent->>'scan_rule', ''),
      case when jsonb_typeof(p_reagent->'scan_segments') = 'array' then p_reagent->'scan_segments' else '[]'::jsonb end,
      coalesce(p_reagent->>'lot_number', ''),
      coalesce(p_reagent->>'production_date', ''),
      coalesce(p_reagent->>'raw_barcode', ''),
      coalesce(p_reagent->>'supplier', ''),
      coalesce(nullif(p_reagent->>'unit_price', '')::numeric, 0)
    ) returning * into saved;

    if opening_stock > 0 then
      update public.reagents set stock_quantity = opening_stock
        where id = saved.id and tenant_id = p_tenant_id returning * into saved;
      insert into public.stock_records (
        tenant_id, reagent_id, type, quantity, lot_number, expiry_date,
        production_date, note, operator, department, reason
      ) values (
        p_tenant_id, saved.id, 'in', opening_stock, saved.lot_number,
        saved.expiry_date, saved.production_date, '新建试剂期初库存',
        coalesce(nullif(p_operator, ''), '管理员'), '检验科', '期初库存'
      );
    end if;
    return saved;
  end if;

  if opening_stock <> 0 then raise exception '编辑试剂资料不能变更库存'; end if;
  update public.reagents set
    code = coalesce(p_reagent->>'code', ''),
    name = coalesce(p_reagent->>'name', ''),
    category = coalesce(p_reagent->>'category', ''),
    specification = coalesce(p_reagent->>'specification', ''),
    manufacturer = coalesce(p_reagent->>'manufacturer', ''),
    unit = coalesce(p_reagent->>'unit', '盒'),
    min_stock = coalesce(nullif(p_reagent->>'min_stock', '')::integer, 0),
    storage_condition = coalesce(p_reagent->>'storage_condition', ''),
    location = coalesce(p_reagent->>'location', ''),
    expiry_date = coalesce(p_reagent->>'expiry_date', ''),
    registration_number = coalesce(p_reagent->>'registration_number', ''),
    notes = coalesce(p_reagent->>'notes', ''),
    scan_rule = coalesce(p_reagent->>'scan_rule', ''),
    scan_segments = case when jsonb_typeof(p_reagent->'scan_segments') = 'array' then p_reagent->'scan_segments' else '[]'::jsonb end,
    lot_number = coalesce(p_reagent->>'lot_number', ''),
    production_date = coalesce(p_reagent->>'production_date', ''),
    raw_barcode = coalesce(p_reagent->>'raw_barcode', ''),
    supplier = coalesce(p_reagent->>'supplier', ''),
    unit_price = coalesce(nullif(p_reagent->>'unit_price', '')::numeric, 0)
  where id = p_id and tenant_id = p_tenant_id
  returning * into saved;
  if saved.id is null then raise exception '试剂不存在或不属于当前检验科'; end if;
  return saved;
end;
$$;

-- 返回完整库存台账汇总出的批次余量，不受前端“最近 200 条记录”显示上限影响。
create or replace function public.list_available_stock_batches(p_tenant_id uuid)
returns table (
  reagent_id bigint,
  lot_number text,
  expiry_date text,
  production_date text,
  quantity bigint
)
language plpgsql stable security definer set search_path = public
as $$
begin
  if p_tenant_id is null or not public.is_tenant_member(p_tenant_id) then
    raise exception '无权访问该检验科';
  end if;

  return query
  with tenant_reagents as (
    select r.id, r.lot_number, r.expiry_date, r.production_date, r.stock_quantity
    from public.reagents r
    where r.tenant_id = p_tenant_id
  ),
  batch_ledger as (
    select
      sr.reagent_id,
      sr.lot_number,
      sr.expiry_date,
      sr.production_date,
      sum(case when sr.type = 'in' then sr.quantity else -sr.quantity end)::bigint as quantity
    from public.stock_records sr
    where sr.tenant_id = p_tenant_id
      and (sr.lot_number <> '' or sr.expiry_date <> '')
    group by sr.reagent_id, sr.lot_number, sr.expiry_date, sr.production_date
  ),
  known_net as (
    select bl.reagent_id, sum(bl.quantity)::bigint as quantity
    from batch_ledger bl
    group by bl.reagent_id
  ),
  combined as (
    select bl.reagent_id, bl.lot_number, bl.expiry_date, bl.production_date, bl.quantity
    from batch_ledger bl
    union all
    select
      r.id,
      r.lot_number,
      r.expiry_date,
      r.production_date,
      (r.stock_quantity - coalesce(kn.quantity, 0))::bigint
    from tenant_reagents r
    left join known_net kn on kn.reagent_id = r.id
  )
  select c.reagent_id, c.lot_number, c.expiry_date, c.production_date, sum(c.quantity)::bigint
  from combined c
  group by c.reagent_id, c.lot_number, c.expiry_date, c.production_date
  having sum(c.quantity) > 0;
end;
$$;

create or replace function public.submit_stock_batch(
  p_tenant_id uuid, p_type text, p_operator text, p_department text, p_reason text, p_items jsonb
)
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  item jsonb;
  reagent_row public.reagents;
  item_quantity integer;
  batch_lot text;
  batch_expiry text;
  batch_production text;
  batch_net bigint;
  known_net bigint;
  available_batch bigint;
  total integer := 0;
begin
  if not public.is_tenant_member(p_tenant_id) then raise exception '无权访问该检验科'; end if;
  if p_type is null or p_type not in ('in', 'out') then raise exception '无效的库存操作'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then raise exception '库存明细格式错误'; end if;

  for item in select * from jsonb_array_elements(p_items) loop
    item_quantity := (item->>'quantity')::integer;
    if item_quantity is null or item_quantity <= 0 then raise exception '数量必须大于 0'; end if;
    batch_lot := coalesce(item->>'lot_number', '');
    batch_expiry := coalesce(item->>'expiry_date', '');
    batch_production := coalesce(item->>'production_date', '');

    select * into reagent_row from public.reagents
      where id = (item->>'reagent_id')::bigint and tenant_id = p_tenant_id for update;
    if reagent_row.id is null then raise exception '试剂不存在或不属于当前检验科'; end if;

    if p_type = 'out' then
      if reagent_row.stock_quantity < item_quantity then
        raise exception '出库数量超过库存：%', reagent_row.name;
      end if;

      select coalesce(sum(case when sr.type = 'in' then sr.quantity else -sr.quantity end), 0)::bigint
      into batch_net
      from public.stock_records sr
      where sr.tenant_id = p_tenant_id
        and sr.reagent_id = reagent_row.id
        and (sr.lot_number <> '' or sr.expiry_date <> '')
        and sr.lot_number = batch_lot
        and sr.expiry_date = batch_expiry
        and sr.production_date = batch_production;

      select coalesce(sum(case when sr.type = 'in' then sr.quantity else -sr.quantity end), 0)::bigint
      into known_net
      from public.stock_records sr
      where sr.tenant_id = p_tenant_id
        and sr.reagent_id = reagent_row.id
        and (sr.lot_number <> '' or sr.expiry_date <> '');

      available_batch := batch_net;
      if batch_lot = reagent_row.lot_number
        and batch_expiry = reagent_row.expiry_date
        and batch_production = reagent_row.production_date then
        available_batch := available_batch + reagent_row.stock_quantity - known_net;
      end if;
      if available_batch < item_quantity then
        raise exception '所选批次库存不足：%', reagent_row.name;
      end if;
    end if;

    update public.reagents
      set stock_quantity = stock_quantity + case when p_type = 'in' then item_quantity else -item_quantity end
      where id = reagent_row.id and tenant_id = p_tenant_id;
    insert into public.stock_records
      (tenant_id, reagent_id, type, quantity, lot_number, expiry_date, production_date, note, operator, department, reason)
    values
      (p_tenant_id, reagent_row.id, p_type, item_quantity,
       batch_lot, batch_expiry, batch_production, coalesce(item->>'note', ''),
       coalesce(p_operator, ''), coalesce(p_department, ''), coalesce(p_reason, ''));
    total := total + 1;
  end loop;
  return total;
end;
$$;

create or replace function public.create_restock_order(p_tenant_id uuid, p_note text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  new_order public.purchase_orders;
  reagent_row public.reagents;
  target_quantity integer;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以创建采购单'; end if;
  insert into public.purchase_orders (tenant_id, status, note, item_count)
  values (p_tenant_id, 'submitted', coalesce(p_note, ''), 0) returning * into new_order;
  for reagent_row in
    select * from public.reagents
    where tenant_id = p_tenant_id and min_stock > 0 and stock_quantity <= min_stock
  loop
    target_quantity := greatest(reagent_row.min_stock * 2 - reagent_row.stock_quantity, 1);
    insert into public.purchase_order_items
      (tenant_id, order_id, reagent_id, quantity, unit, name, manufacturer, specification, supplier)
    values
      (p_tenant_id, new_order.id, reagent_row.id, target_quantity,
       reagent_row.unit, reagent_row.name, reagent_row.manufacturer, reagent_row.specification, reagent_row.supplier);
  end loop;
  update public.purchase_orders
    set item_count = (select count(*) from public.purchase_order_items where order_id = new_order.id and tenant_id = p_tenant_id)
    where id = new_order.id and tenant_id = p_tenant_id;
  return jsonb_build_object('id', new_order.id);
end;
$$;

create or replace function public.receive_purchase_order(p_tenant_id uuid, p_id bigint, p_operator text)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  order_row public.purchase_orders;
  item_row public.purchase_order_items;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以确认到货'; end if;
  select * into order_row from public.purchase_orders where id = p_id and tenant_id = p_tenant_id for update;
  if order_row.id is null then raise exception '采购单不存在'; end if;
  if order_row.status <> 'submitted' then return; end if;
  for item_row in select * from public.purchase_order_items where order_id = p_id and tenant_id = p_tenant_id loop
    update public.reagents set stock_quantity = stock_quantity + item_row.quantity
      where id = item_row.reagent_id and tenant_id = p_tenant_id;
    insert into public.stock_records (tenant_id, reagent_id, type, quantity, lot_number, note, operator, department, reason)
    values (p_tenant_id, item_row.reagent_id, 'in', item_row.quantity, '', '采购单到货', coalesce(p_operator, ''), '检验科', '采购入库');
  end loop;
  update public.purchase_orders set status = 'received' where id = p_id and tenant_id = p_tenant_id;
end;
$$;

-- 自助创建检验科不对前端开放：新科室只能通过平台管理员的 create_platform_tenant 开通。
revoke all on function public.create_tenant(text, text) from public, anon, authenticated;
revoke all on function public.create_platform_tenant(text, text) from public;
grant execute on function public.create_platform_tenant(text, text) to authenticated;
grant execute on function public.is_platform_admin() to authenticated;
revoke all on function public.create_tenant_invite(uuid) from public;
grant execute on function public.create_tenant_invite(uuid) to authenticated;
revoke all on function public.accept_tenant_invite(text) from public;
grant execute on function public.accept_tenant_invite(text) to authenticated;
revoke all on function public.list_available_stock_batches(uuid) from public, anon;
revoke all on function public.save_reagent(uuid, bigint, jsonb, integer, text) from public, anon;
grant execute on function public.save_reagent(uuid, bigint, jsonb, integer, text) to authenticated;
grant execute on function public.list_available_stock_batches(uuid) to authenticated;
grant execute on function public.submit_stock_batch(uuid, text, text, text, text, jsonb) to authenticated;
grant execute on function public.create_restock_order(uuid, text) to authenticated;
grant execute on function public.receive_purchase_order(uuid, bigint, text) to authenticated;

-- ── 8) 自检：应看到下面 7 张表，初始化即完成 ─────────────────────────

select table_name
from information_schema.tables
where table_schema = 'public'
order by table_name;
