-- =====================================================================
-- 权盾智检 · 数据库一次性初始化（全新多租户，从零开始）
--
-- ⚠ 警告：本脚本会删除现有全部测试数据（试剂、库存、采购单），不可恢复！
--
-- 使用方法：
--   1. 打开 https://supabase.com/dashboard/project/eqgrtoeivuykemfferwb/sql/new
--   2. 粘贴本文件全部内容
--   3. 点击 Run，看到最后的表清单即初始化完成
-- =====================================================================

create extension if not exists pgcrypto;

-- ── 1) 清理旧的测试数据和旧版函数 ────────────────────────────────────

drop table if exists public.purchase_order_items cascade;
drop table if exists public.purchase_orders cascade;
drop table if exists public.stock_records cascade;
drop table if exists public.reagents cascade;
drop table if exists public.tenant_invites cascade;
drop table if exists public.tenant_members cascade;
drop table if exists public.tenants cascade;

do $$
declare fn record;
begin
  for fn in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'is_tenant_member', 'is_tenant_admin', 'claim_default_tenant',
        'create_tenant', 'create_tenant_invite', 'accept_tenant_invite',
        'submit_stock_batch', 'create_restock_order', 'receive_purchase_order'
      )
  loop
    execute format('drop function %s cascade', fn.signature);
  end loop;
end $$;

-- ── 2) 租户（检验科）、成员、邀请码 ──────────────────────────────────

create table public.tenants (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  code        text not null,
  status      text not null default 'active' check (status in ('active', 'disabled')),
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);
create unique index tenants_code_lower_idx on public.tenants (lower(code));

create table public.tenant_members (
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  role       text not null default 'employee' check (role in ('admin', 'employee')),
  created_at timestamptz not null default now(),
  primary key (tenant_id, user_id)
);
create index tenant_members_user_idx on public.tenant_members (user_id);

create table public.tenant_invites (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  code        text not null unique,
  role        text not null default 'employee' check (role = 'employee'),
  created_by  uuid not null references auth.users(id) on delete restrict,
  expires_at  timestamptz not null default (now() + interval '7 days'),
  used_by     uuid references auth.users(id) on delete set null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index tenant_invites_tenant_idx on public.tenant_invites (tenant_id, created_at desc);

-- ── 3) 业务表（自带 tenant_id，从零开始，不含任何测试数据）────────────

create table public.reagents (
  id                  bigint generated by default as identity primary key,
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  code                text not null default '',
  name                text not null,
  category            text not null default '',
  specification       text not null default '',
  manufacturer        text not null default '',
  unit                text not null default '盒',
  stock_quantity      integer not null default 0,
  min_stock           integer not null default 0,
  storage_condition   text not null default '',
  location            text not null default '',
  expiry_date         text not null default '',
  registration_number text not null default '',
  notes               text not null default '',
  scan_rule           text not null default '',
  scan_segments       jsonb not null default '[]'::jsonb,
  lot_number          text not null default '',
  production_date     text not null default '',
  raw_barcode         text not null default '',
  supplier            text not null default '',
  unit_price          numeric(12, 2) not null default 0,
  created_at          timestamptz not null default now()
);
create unique index reagents_tenant_code_idx on public.reagents (tenant_id, code) where code <> '';
create index reagents_tenant_idx on public.reagents (tenant_id, id);

create table public.stock_records (
  id              bigint generated by default as identity primary key,
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  reagent_id      bigint not null references public.reagents(id) on delete restrict,
  type            text not null check (type in ('in', 'out')),
  quantity        integer not null check (quantity > 0),
  lot_number      text not null default '',
  expiry_date     text not null default '',
  production_date text not null default '',
  note            text not null default '',
  operator        text not null default '',
  department      text not null default '',
  reason          text not null default '',
  created_at      timestamptz not null default now()
);
create index stock_records_tenant_idx on public.stock_records (tenant_id, created_at desc);

create table public.purchase_orders (
  id         bigint generated by default as identity primary key,
  tenant_id  uuid not null references public.tenants(id) on delete cascade,
  status     text not null default 'submitted' check (status in ('submitted', 'received', 'cancelled')),
  note       text not null default '',
  item_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index purchase_orders_tenant_idx on public.purchase_orders (tenant_id, created_at desc);

create table public.purchase_order_items (
  id            bigint generated by default as identity primary key,
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  order_id      bigint not null references public.purchase_orders(id) on delete cascade,
  reagent_id    bigint not null references public.reagents(id) on delete restrict,
  quantity      integer not null check (quantity > 0),
  unit          text not null default '',
  name          text not null default '',
  manufacturer  text not null default '',
  specification text not null default '',
  supplier      text not null default ''
);
create index purchase_order_items_tenant_idx on public.purchase_order_items (tenant_id, order_id);

-- ── 4) 成员关系判定函数 ──────────────────────────────────────────────

create or replace function public.is_tenant_member(p_tenant_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.tenant_members m
    where m.tenant_id = p_tenant_id and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_tenant_admin(p_tenant_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.tenant_members m
    where m.tenant_id = p_tenant_id and m.user_id = auth.uid() and m.role = 'admin'
  );
$$;

-- ── 5) 创建检验科 / 邀请码 RPC ───────────────────────────────────────

create or replace function public.create_tenant(p_name text, p_code text)
returns public.tenants
language plpgsql security definer set search_path = public
as $$
declare
  result public.tenants;
  normalized_code text := upper(trim(p_code));
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if trim(coalesce(p_name, '')) = '' or normalized_code = '' then raise exception '检验科名称和编码不能为空'; end if;
  if exists (select 1 from public.tenant_members where user_id = auth.uid()) then
    raise exception '该账号已经加入检验科';
  end if;
  insert into public.tenants (name, code, created_by)
  values (trim(p_name), normalized_code, auth.uid())
  returning * into result;
  insert into public.tenant_members (tenant_id, user_id, role)
  values (result.id, auth.uid(), 'admin');
  return result;
end;
$$;

create or replace function public.create_tenant_invite(p_tenant_id uuid)
returns text
language plpgsql security definer set search_path = public
as $$
declare
  invite_code text;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以生成邀请码'; end if;
  invite_code := upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 10));
  insert into public.tenant_invites (tenant_id, code, created_by)
  values (p_tenant_id, invite_code, auth.uid());
  return invite_code;
end;
$$;

create or replace function public.accept_tenant_invite(p_code text)
returns public.tenants
language plpgsql security definer set search_path = public
as $$
declare
  invite_row public.tenant_invites;
  result public.tenants;
begin
  if auth.uid() is null then raise exception '请先登录'; end if;
  if exists (select 1 from public.tenant_members where user_id = auth.uid()) then
    raise exception '该账号已经加入检验科';
  end if;
  select * into invite_row from public.tenant_invites
  where code = upper(trim(p_code)) and used_by is null and expires_at > now()
  for update;
  if invite_row.id is null then raise exception '邀请码无效或已过期'; end if;
  insert into public.tenant_members (tenant_id, user_id, role)
  values (invite_row.tenant_id, auth.uid(), 'employee');
  update public.tenant_invites set used_by = auth.uid(), used_at = now() where id = invite_row.id;
  select * into result from public.tenants where id = invite_row.tenant_id;
  return result;
end;
$$;

-- ── 6) 行级安全（RLS）：只能访问所属检验科的数据 ─────────────────────

alter table public.tenants enable row level security;
alter table public.tenant_members enable row level security;
alter table public.tenant_invites enable row level security;
alter table public.reagents enable row level security;
alter table public.stock_records enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;

create policy tenants_member_select on public.tenants
  for select using (public.is_tenant_member(id));

create policy tenant_members_self_or_admin_select on public.tenant_members
  for select using (user_id = auth.uid() or public.is_tenant_admin(tenant_id));

create policy tenant_invites_admin_select on public.tenant_invites
  for select using (public.is_tenant_admin(tenant_id));

create policy reagents_member_select on public.reagents
  for select using (public.is_tenant_member(tenant_id));
create policy reagents_admin_insert on public.reagents
  for insert with check (public.is_tenant_admin(tenant_id));
create policy reagents_admin_update on public.reagents
  for update using (public.is_tenant_admin(tenant_id)) with check (public.is_tenant_admin(tenant_id));
create policy reagents_admin_delete on public.reagents
  for delete using (public.is_tenant_admin(tenant_id));

create policy stock_records_member_select on public.stock_records
  for select using (public.is_tenant_member(tenant_id));
create policy purchase_orders_member_select on public.purchase_orders
  for select using (public.is_tenant_member(tenant_id));
create policy purchase_order_items_member_select on public.purchase_order_items
  for select using (public.is_tenant_member(tenant_id));

-- 表级权限：库存记录和采购单只能通过下面的 RPC 写入，员工不能直接改。
grant select on public.tenants, public.tenant_members, public.tenant_invites to authenticated;
grant select on public.reagents, public.stock_records, public.purchase_orders, public.purchase_order_items to authenticated;
grant insert, update, delete on public.reagents to authenticated;
revoke insert, update, delete on public.stock_records, public.purchase_orders, public.purchase_order_items from anon, authenticated;
revoke insert, update, delete on public.tenants, public.tenant_members, public.tenant_invites from anon, authenticated;

-- ── 7) 业务 RPC（函数内再次校验成员/管理员身份）──────────────────────

create or replace function public.submit_stock_batch(
  p_tenant_id uuid, p_type text, p_operator text, p_department text, p_reason text, p_items jsonb
)
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  item jsonb;
  reagent_row public.reagents;
  item_quantity integer;
  total integer := 0;
begin
  if not public.is_tenant_member(p_tenant_id) then raise exception '无权访问该检验科'; end if;
  if p_type not in ('in', 'out') then raise exception '无效的库存操作'; end if;
  for item in select * from jsonb_array_elements(p_items) loop
    item_quantity := (item->>'quantity')::integer;
    if item_quantity is null or item_quantity <= 0 then raise exception '数量必须大于 0'; end if;
    select * into reagent_row from public.reagents
      where id = (item->>'reagent_id')::bigint and tenant_id = p_tenant_id for update;
    if reagent_row.id is null then raise exception '试剂不存在或不属于当前检验科'; end if;
    if p_type = 'out' and reagent_row.stock_quantity < item_quantity then
      raise exception '出库数量超过库存：%', reagent_row.name;
    end if;
    update public.reagents
      set stock_quantity = stock_quantity + case when p_type = 'in' then item_quantity else -item_quantity end
      where id = reagent_row.id and tenant_id = p_tenant_id;
    insert into public.stock_records
      (tenant_id, reagent_id, type, quantity, lot_number, expiry_date, production_date, note, operator, department, reason)
    values
      (p_tenant_id, reagent_row.id, p_type, item_quantity,
       coalesce(item->>'lot_number', ''), coalesce(item->>'expiry_date', ''),
       coalesce(item->>'production_date', ''), coalesce(item->>'note', ''),
       coalesce(p_operator, ''), coalesce(p_department, ''), coalesce(p_reason, ''));
    total := total + 1;
  end loop;
  return total;
end;
$$;

create or replace function public.create_restock_order(p_tenant_id uuid, p_note text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  new_order public.purchase_orders;
  reagent_row public.reagents;
  target_quantity integer;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以创建采购单'; end if;
  insert into public.purchase_orders (tenant_id, status, note, item_count)
  values (p_tenant_id, 'submitted', coalesce(p_note, ''), 0) returning * into new_order;
  for reagent_row in
    select * from public.reagents
    where tenant_id = p_tenant_id and min_stock > 0 and stock_quantity <= min_stock
  loop
    target_quantity := greatest(reagent_row.min_stock * 2 - reagent_row.stock_quantity, 1);
    insert into public.purchase_order_items
      (tenant_id, order_id, reagent_id, quantity, unit, name, manufacturer, specification, supplier)
    values
      (p_tenant_id, new_order.id, reagent_row.id, target_quantity,
       reagent_row.unit, reagent_row.name, reagent_row.manufacturer, reagent_row.specification, reagent_row.supplier);
  end loop;
  update public.purchase_orders
    set item_count = (select count(*) from public.purchase_order_items where order_id = new_order.id and tenant_id = p_tenant_id)
    where id = new_order.id and tenant_id = p_tenant_id;
  return jsonb_build_object('id', new_order.id);
end;
$$;

create or replace function public.receive_purchase_order(p_tenant_id uuid, p_id bigint, p_operator text)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  order_row public.purchase_orders;
  item_row public.purchase_order_items;
begin
  if not public.is_tenant_admin(p_tenant_id) then raise exception '只有检验科管理员可以确认到货'; end if;
  select * into order_row from public.purchase_orders where id = p_id and tenant_id = p_tenant_id for update;
  if order_row.id is null then raise exception '采购单不存在'; end if;
  if order_row.status <> 'submitted' then return; end if;
  for item_row in select * from public.purchase_order_items where order_id = p_id and tenant_id = p_tenant_id loop
    update public.reagents set stock_quantity = stock_quantity + item_row.quantity
      where id = item_row.reagent_id and tenant_id = p_tenant_id;
    insert into public.stock_records (tenant_id, reagent_id, type, quantity, lot_number, note, operator, department, reason)
    values (p_tenant_id, item_row.reagent_id, 'in', item_row.quantity, '', '采购单到货', coalesce(p_operator, ''), '检验科', '采购入库');
  end loop;
  update public.purchase_orders set status = 'received' where id = p_id and tenant_id = p_tenant_id;
end;
$$;

revoke all on function public.create_tenant(text, text) from public;
grant execute on function public.create_tenant(text, text) to anon, authenticated;
revoke all on function public.create_tenant_invite(uuid) from public;
grant execute on function public.create_tenant_invite(uuid) to authenticated;
revoke all on function public.accept_tenant_invite(text) from public;
grant execute on function public.accept_tenant_invite(text) to authenticated;
grant execute on function public.submit_stock_batch(uuid, text, text, text, text, jsonb) to authenticated;
grant execute on function public.create_restock_order(uuid, text) to authenticated;
grant execute on function public.receive_purchase_order(uuid, bigint, text) to authenticated;

-- ── 8) 自检：应看到下面 7 张表，初始化即完成 ─────────────────────────

select table_name
from information_schema.tables
where table_schema = 'public'
order by table_name;
